### PR TITLE
This is a searchable select box feature

### PR DESCRIPTION
**Pull request by tomhero**
I very like your Labyrinth Team Optimizer, thus for more confident UX I recommend you to use a searchable selected box, sir.

To done this job, I use [Select2](https://select2.org/) and I test it in all responsive ratio, So if you like this you can accept my work otherwise leave a comment.

Moreover, I separated your CSS and JS file into `style.css` and `script.js`

### CODE REVIEW

**Comment by budandan** [comment]
Hey sorry I’m just seeing this. I had no idea people would make PRs for this. I’ll pull your commit and test it out. Thanks!

**Comment by tomhero** [comment]
> Hey sorry I’m just seeing this. I had no idea people would make PRs for this. I’ll pull your commit and test it out. Thanks!

Thanks for your response, I

**Comment by tomhero** [comment]
> Hey sorry I’m just seeing this. I had no idea people would make PRs for this. I’ll pull your commit and test it out. Thanks!

Thanks for your response ;)

**Comment by budandan** [comment]
It is bugged when I add two or more heroes using your selectize menu. For example, I add both Achates and Angelica to the roster simultaneously - but it adds them graphically, but I cannot delete Angelica from the roster because she is not found.

**Comment by tomhero** [comment]
I found that binding `onclick` function when adding hero to the roster is missing double quote, Could you please check it out here. https://github.com/budandan/budandan.github.io/blob/d5226d39204d652545d545f112d772434f6d8dc6/e7-lab-team-optimizer/index.html#L248

So it may cause the undefined error when a user clicks the remove button, I try it with `Dark Corvus` **on your production website** then console tell me `index.html:1 Uncaught ReferenceError: Dark_Corvus is not defined`

**Comment by budandan** [comment]
Yep thats an error I recently found as well. Im going to resolve these conflicts and push your code up

**Pull request merged**
